/* Generated by re2c 0.13.5 on Fri May 31 11:10:47 2013 */
#line 1 "test.re2c"
char *scan(char *p)
{

#line 7 "<stdout>"
	{
		unsigned char yych;

		yych = (unsigned char)*p;
		if (yych <= '/') goto yy4;
		if (yych >= ':') goto yy4;
		++p;
		yych = (unsigned char)*p;
		goto yy7;
yy3:
#line 9 "test.re2c"
		{return p;}
#line 20 "<stdout>"
yy4:
		++p;
#line 10 "test.re2c"
		{return (char*)0;}
#line 25 "<stdout>"
yy6:
		++p;
		yych = (unsigned char)*p;
yy7:
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy6;
		goto yy3;
	}
#line 11 "test.re2c"

}	
